#include "FB_FuzzyController.h"
#include <stddef.h>

#define EPS (0.000001f)
#define FMAXV (3.402823466e+38F)
#define PWM_MIN (0.0f)
#define PWM_MAX (1000.0f)
#define MS_TO_S (0.001f)

static float clampf(float v,float lo,float hi){if(v<lo)return lo;if(v>hi)return hi;return v;}
static float absf(float v){return(v>=0.0f)?v:-v;}
static float maxf(float a,float b){return(a>b)?a:b;}
static bool finitef(float v){return(v==v)&&(v<FMAXV)&&(v>-FMAXV);}
static float ms2s(uint32_t ms){return(float)ms*MS_TO_S;}

static bool valid_sample(uint32_t ms){return(ms>=FUZZY_CONTROLLER_SAMPLE_TIME_MIN_MS)&&(ms<=FUZZY_CONTROLLER_SAMPLE_TIME_MAX_MS);}
static bool valid_derivative(const FB_FuzzyController_t*fb){return fb&&finitef(fb->config.DErrorFilterTau_s)&&fb->config.DErrorFilterTau_s>=0.0f&&fb->config.DErrorFilterTau_s<=FUZZY_CONTROLLER_DERROR_FILTER_TAU_MAX_S&&finitef(fb->config.DErrorDeadband_c_per_s)&&fb->config.DErrorDeadband_c_per_s>=0.0f&&fb->config.DErrorDeadband_c_per_s<=FUZZY_CONTROLLER_DERROR_DEADBAND_MAX;}
static bool valid_boost(const FB_FuzzyController_t*fb){return fb&&finitef(fb->config.BoostEnterError_c)&&finitef(fb->config.BoostExitError_c)&&fb->config.BoostEnterError_c>=0.0f&&fb->config.BoostExitError_c>=0.0f&&fb->config.BoostExitError_c<=fb->config.BoostEnterError_c;}
static bool valid_approach(const FB_FuzzyController_t*fb){return fb&&finitef(fb->config.FullPowerErrorRatio)&&finitef(fb->config.PrecisionErrorRatio)&&finitef(fb->config.FullPowerErrorMin_c)&&finitef(fb->config.PrecisionErrorMin_c)&&finitef(fb->config.ApproachDownSlewRate_pwm_per_s)&&fb->config.FullPowerErrorRatio>0.0f&&fb->config.FullPowerErrorRatio<=FUZZY_CONTROLLER_APPROACH_RATIO_MAX&&fb->config.PrecisionErrorRatio>=0.0f&&fb->config.PrecisionErrorRatio<fb->config.FullPowerErrorRatio&&fb->config.FullPowerErrorMin_c>0.0f&&fb->config.PrecisionErrorMin_c>=0.0f&&fb->config.PrecisionErrorMin_c<fb->config.FullPowerErrorMin_c&&fb->config.ApproachDownSlewRate_pwm_per_s>=0.0f&&fb->config.ApproachDownSlewRate_pwm_per_s<=FUZZY_CONTROLLER_APPROACH_SLEW_MAX;}
static bool valid_config(const FB_FuzzyController_t*fb){return fb&&valid_sample(fb->config.SampleTime_ms)&&finitef(fb->config.Ts)&&fb->config.Ts>EPS&&valid_derivative(fb)&&valid_boost(fb)&&valid_approach(fb)&&finitef(fb->config.OutputMin)&&finitef(fb->config.OutputMax)&&fb->config.OutputMin>=PWM_MIN&&fb->config.OutputMax<=PWM_MAX&&fb->config.OutputMin<fb->config.OutputMax;}

static void clear_derivative(FB_FuzzyController_t*fb){fb->state.RawDError=0.0f;fb->state.FilteredDError=0.0f;fb->state.dError=0.0f;fb->scaling.State.dError=0.0f;fb->scaling.State.PVRate=0.0f;fb->scaling.State.NormalizedDError=0.0f;}
static void clear_approach(FB_FuzzyController_t*fb){fb->state.FullPowerError_c=0.0f;fb->state.PrecisionError_c=0.0f;fb->state.ApproachBlend=0.0f;fb->state.BoostActive=false;fb->state.ApproachActive=false;}

static float filter_derror(FB_FuzzyController_t*fb,float raw){float f,a,m;if(!finitef(raw))return 0.0f;if(fb->config.DErrorFilterTau_s<=EPS)f=raw;else{a=fb->config.Ts/(fb->config.DErrorFilterTau_s+fb->config.Ts);a=clampf(a,0.0f,1.0f);f=fb->state.FilteredDError+a*(raw-fb->state.FilteredDError);}if(!finitef(f))f=0.0f;fb->state.FilteredDError=f;m=absf(f);if(m<=fb->config.DErrorDeadband_c_per_s)return 0.0f;m-=fb->config.DErrorDeadband_c_per_s;return(f>=0.0f)?m:-m;}

static void force_min(FB_FuzzyController_t*fb){float m=(fb&&finitef(fb->config.OutputMin))?clampf(fb->config.OutputMin,PWM_MIN,PWM_MAX):PWM_MIN;fb->state.PWM=m;clear_approach(fb);fb->output.state.pwmFF=0.0f;fb->output.state.fuzzyCorrection=0.0f;fb->output.state.targetPWM=m;fb->output.state.outputPWM=m;fb->output.state.previousPWM=m;fb->hybridOutput.state.feedForwardPWM=0.0f;fb->hybridOutput.state.fuzzyCorrectionPWM=0.0f;fb->hybridOutput.state.biasPWM=0.0f;fb->hybridOutput.state.targetPWM=m;fb->hybridOutput.state.outputPWM=m;}

static void update_zones(FB_FuzzyController_t*fb){bool was=fb->state.BoostActive;float r;if(!fb->config.EnableBoost){clear_approach(fb);return;}if(fb->config.EnablePercentApproach){float s=absf(fb->state.SV);fb->state.FullPowerError_c=maxf(s*fb->config.FullPowerErrorRatio,fb->config.FullPowerErrorMin_c);fb->state.PrecisionError_c=maxf(s*fb->config.PrecisionErrorRatio,fb->config.PrecisionErrorMin_c);if(fb->state.Error>fb->state.FullPowerError_c){fb->state.BoostActive=true;fb->state.ApproachActive=false;fb->state.ApproachBlend=1.0f;}else if(fb->state.Error>fb->state.PrecisionError_c){fb->state.BoostActive=false;fb->state.ApproachActive=true;r=fb->state.FullPowerError_c-fb->state.PrecisionError_c;fb->state.ApproachBlend=(r>EPS)?clampf((fb->state.Error-fb->state.PrecisionError_c)/r,0.0f,1.0f):0.0f;}else{fb->state.BoostActive=false;fb->state.ApproachActive=false;fb->state.ApproachBlend=0.0f;}}else{fb->state.FullPowerError_c=fb->config.BoostEnterError_c;fb->state.PrecisionError_c=fb->config.BoostExitError_c;fb->state.ApproachActive=false;fb->state.ApproachBlend=0.0f;if(fb->state.BoostActive){if(fb->state.Error<fb->config.BoostExitError_c)fb->state.BoostActive=false;}else if(fb->state.Error>fb->config.BoostEnterError_c)fb->state.BoostActive=true;}if(!was&&fb->state.BoostActive)fb->hybridOutput.state.biasPWM=0.0f;}

static void apply_boost(FB_FuzzyController_t*fb){float p=clampf(PWM_MAX,fb->config.OutputMin,fb->config.OutputMax);fb->state.PWM=p;fb->state.ApproachBlend=1.0f;fb->hybridOutput.state.targetPWM=p;fb->hybridOutput.state.outputPWM=p;fb->output.state.targetPWM=p;fb->output.state.outputPWM=p;fb->output.state.previousPWM=p;}

static void apply_soft_landing(FB_FuzzyController_t*fb,float previous){float full,native,target,final,maxDrop,minAllowed;if(!fb->state.ApproachActive)return;full=clampf(PWM_MAX,fb->config.OutputMin,fb->config.OutputMax);native=clampf(fb->state.PWM,fb->config.OutputMin,fb->config.OutputMax);target=fb->state.ApproachBlend*full+(1.0f-fb->state.ApproachBlend)*native;target=clampf(target,fb->config.OutputMin,fb->config.OutputMax);final=target;if(fb->config.ApproachDownSlewRate_pwm_per_s>0.0f&&target<previous){maxDrop=fb->config.ApproachDownSlewRate_pwm_per_s*fb->config.Ts;minAllowed=previous-maxDrop;if(final<minAllowed)final=minAllowed;}final=clampf(final,fb->config.OutputMin,fb->config.OutputMax);fb->state.PWM=final;if(fb->config.UseHybridOutput){fb->hybridOutput.state.targetPWM=target;fb->hybridOutput.state.outputPWM=final;}else{fb->output.state.targetPWM=target;fb->output.state.outputPWM=final;fb->output.state.previousPWM=final;}}

void FB_FuzzyController_LoadIdentifiedFeedForward(FB_FuzzyController_t*fb){if(!fb)return;fb->hybridOutput.config.ffSize=4U;fb->hybridOutput.config.ffTable[0].temperature=25.00f;fb->hybridOutput.config.ffTable[0].pwm=0.0f;fb->hybridOutput.config.ffTable[1].temperature=93.40f;fb->hybridOutput.config.ffTable[1].pwm=200.0f;fb->hybridOutput.config.ffTable[2].temperature=149.15f;fb->hybridOutput.config.ffTable[2].pwm=500.0f;fb->hybridOutput.config.ffTable[3].temperature=160.84f;fb->hybridOutput.config.ffTable[3].pwm=800.0f;fb->hybridOutput.config.enableFeedForward=true;}

void FB_FuzzyController_Init(FB_FuzzyController_t*fb){if(!fb)return;fb->config.SampleTime_ms=FUZZY_CONTROLLER_SAMPLE_TIME_DEFAULT_MS;fb->config.Ts=ms2s(fb->config.SampleTime_ms);fb->config.DErrorFilterTau_s=FUZZY_CONTROLLER_DERROR_FILTER_TAU_DEFAULT_S;fb->config.DErrorDeadband_c_per_s=FUZZY_CONTROLLER_DERROR_DEADBAND_DEFAULT;fb->config.EnableBoost=true;fb->config.BoostEnterError_c=FUZZY_CONTROLLER_BOOST_ENTER_DEFAULT_C;fb->config.BoostExitError_c=FUZZY_CONTROLLER_BOOST_EXIT_DEFAULT_C;fb->config.EnablePercentApproach=true;fb->config.FullPowerErrorRatio=FUZZY_CONTROLLER_APPROACH_FULL_RATIO_DEFAULT;fb->config.PrecisionErrorRatio=FUZZY_CONTROLLER_APPROACH_PRECISION_RATIO_DEFAULT;fb->config.FullPowerErrorMin_c=FUZZY_CONTROLLER_APPROACH_FULL_MIN_C;fb->config.PrecisionErrorMin_c=FUZZY_CONTROLLER_APPROACH_PRECISION_MIN_C;fb->config.ApproachDownSlewRate_pwm_per_s=FUZZY_CONTROLLER_APPROACH_DOWN_SLEW_DEFAULT;fb->config.UseHybridOutput=false;fb->config.Enable=true;fb->config.OutputMin=PWM_MIN;fb->config.OutputMax=PWM_MAX;fb->state.SV=0.0f;fb->state.PV=0.0f;fb->state.Error=0.0f;fb->state.RawDError=0.0f;fb->state.FilteredDError=0.0f;fb->state.dError=0.0f;fb->state.PWM=0.0f;fb->state.Centroid=0.0f;fb->state.initialized=false;fb->state.firstRun=true;clear_approach(fb);FB_FuzzyScaling_Init(&fb->scaling);FB_FuzzyMembership_Init(&fb->membership);FB_FuzzyRule_Init(&fb->ruleEngine);FB_FuzzyOutput_Init(&fb->output);FB_FuzzyHybridOutput_Init(&fb->hybridOutput);FB_FuzzyController_LoadIdentifiedFeedForward(fb);fb->scaling.Config.Ts=fb->config.Ts;fb->output.config.pwmMin=fb->config.OutputMin;fb->output.config.pwmMax=fb->config.OutputMax;fb->hybridOutput.config.pwmMin=fb->config.OutputMin;fb->hybridOutput.config.pwmMax=fb->config.OutputMax;FB_FuzzyController_LoadDefaultRule(fb);fb->state.initialized=true;}

bool FB_FuzzyController_SetSampleTime(FB_FuzzyController_t*fb,uint32_t ms){if(!fb||!valid_sample(ms))return false;fb->config.SampleTime_ms=ms;fb->config.Ts=ms2s(ms);fb->scaling.Config.Ts=fb->config.Ts;fb->state.firstRun=true;clear_derivative(fb);return true;}
uint32_t FB_FuzzyController_GetSampleTime(const FB_FuzzyController_t*fb){return fb?fb->config.SampleTime_ms:0U;}

bool FB_FuzzyController_SetDerivativeFilter(FB_FuzzyController_t*fb,float tau,float db){if(!fb||!finitef(tau)||tau<0.0f||tau>FUZZY_CONTROLLER_DERROR_FILTER_TAU_MAX_S||!finitef(db)||db<0.0f||db>FUZZY_CONTROLLER_DERROR_DEADBAND_MAX)return false;fb->config.DErrorFilterTau_s=tau;fb->config.DErrorDeadband_c_per_s=db;fb->state.firstRun=true;clear_derivative(fb);return true;}

bool FB_FuzzyController_SetBoostConfig(FB_FuzzyController_t*fb,bool en,float enter,float exit){if(!fb||!finitef(enter)||!finitef(exit)||enter<0.0f||exit<0.0f||exit>enter)return false;fb->config.EnableBoost=en;fb->config.BoostEnterError_c=enter;fb->config.BoostExitError_c=exit;if(!en)clear_approach(fb);return true;}

bool FB_FuzzyController_SetApproachConfig(FB_FuzzyController_t*fb,bool en,float fullRatio,float precisionRatio,float fullMin,float precisionMin,float slew){FuzzyControllerConfig_t old;if(!fb)return false;old=fb->config;fb->config.EnablePercentApproach=en;fb->config.FullPowerErrorRatio=fullRatio;fb->config.PrecisionErrorRatio=precisionRatio;fb->config.FullPowerErrorMin_c=fullMin;fb->config.PrecisionErrorMin_c=precisionMin;fb->config.ApproachDownSlewRate_pwm_per_s=slew;if(!valid_approach(fb)){fb->config=old;return false;}clear_approach(fb);return true;}

void FB_FuzzyController_EnableHybridOutput(FB_FuzzyController_t*fb,bool en){float cur;if(!fb)return;cur=clampf(fb->state.PWM,fb->config.OutputMin,fb->config.OutputMax);fb->config.UseHybridOutput=en;fb->output.state.outputPWM=cur;fb->output.state.previousPWM=cur;fb->hybridOutput.state.outputPWM=cur;fb->hybridOutput.state.targetPWM=cur;}

float FB_FuzzyController_Run(FB_FuzzyController_t*fb,float SV,float PV){float rule,raw,previous;if(!fb)return 0.0f;if(!fb->state.initialized)FB_FuzzyController_Init(fb);if(!valid_config(fb)){force_min(fb);fb->state.Error=0.0f;clear_derivative(fb);fb->state.firstRun=true;return fb->state.PWM;}if(!finitef(SV)||!finitef(PV)){fb->state.SV=SV;fb->state.PV=PV;fb->state.Error=0.0f;clear_derivative(fb);force_min(fb);fb->state.firstRun=true;return fb->state.PWM;}if(!fb->config.Enable){force_min(fb);clear_derivative(fb);fb->state.firstRun=true;return fb->state.PWM;}previous=clampf(fb->state.PWM,fb->config.OutputMin,fb->config.OutputMax);fb->config.Ts=ms2s(fb->config.SampleTime_ms);fb->scaling.Config.Ts=fb->config.Ts;fb->output.config.pwmMin=fb->config.OutputMin;fb->output.config.pwmMax=fb->config.OutputMax;fb->hybridOutput.config.pwmMin=fb->config.OutputMin;fb->hybridOutput.config.pwmMax=fb->config.OutputMax;fb->state.SV=SV;fb->state.PV=PV;fb->state.Error=SV-PV;if(fb->state.firstRun){fb->scaling.State.PreviousError=fb->state.Error;fb->scaling.State.PreviousPV=PV;clear_derivative(fb);fb->state.firstRun=false;}FB_FuzzyScaling_Run(&fb->scaling,SV,PV);fb->state.Error=fb->scaling.State.Error;raw=-fb->scaling.State.PVRate;fb->state.RawDError=raw;fb->state.dError=filter_derror(fb,raw);fb->scaling.State.dError=fb->state.dError;fb->scaling.State.NormalizedDError=FB_FuzzyScaling_NormalizeDError(fb->state.dError,fb->scaling.State.Kde);FB_FuzzyMembership_Run(&fb->membership,fb->scaling.State.NormalizedError,fb->scaling.State.NormalizedDError);FB_FuzzyRule_Run(&fb->ruleEngine,&fb->membership);rule=clampf(fb->ruleEngine.Result.RuleOutput,fb->config.OutputMin,fb->config.OutputMax);update_zones(fb);if(fb->config.UseHybridOutput)fb->state.PWM=FB_FuzzyHybridOutput_Run(&fb->hybridOutput,SV,PV,rule,fb->config.Ts);else fb->state.PWM=FB_FuzzyOutput_RunAbsolute(&fb->output,SV,rule,fb->config.Ts);if(fb->state.BoostActive)apply_boost(fb);else if(fb->state.ApproachActive)apply_soft_landing(fb,previous);if(fb->config.OutputMax>fb->config.OutputMin+EPS)fb->state.Centroid=((rule-fb->config.OutputMin)/(fb->config.OutputMax-fb->config.OutputMin))*2.0f-1.0f;else fb->state.Centroid=0.0f;return fb->state.PWM;}

void FB_FuzzyController_Reset(FB_FuzzyController_t*fb){if(!fb)return;FB_FuzzyScaling_Reset(&fb->scaling);FB_FuzzyMembership_Reset(&fb->membership);FB_FuzzyRule_Reset(&fb->ruleEngine);FB_FuzzyHybridOutput_Reset(&fb->hybridOutput);force_min(fb);fb->state.SV=0.0f;fb->state.PV=0.0f;fb->state.Error=0.0f;clear_derivative(fb);fb->state.Centroid=0.0f;clear_approach(fb);fb->state.firstRun=true;fb->config.Ts=ms2s(fb->config.SampleTime_ms);fb->scaling.Config.Ts=fb->config.Ts;}
void FB_FuzzyController_LoadDefaultRule(FB_FuzzyController_t*fb){if(fb)FB_FuzzyRule_LoadDefault(&fb->ruleEngine);}
bool FB_FuzzyController_SetRule(FB_FuzzyController_t*fb,uint8_t e,uint8_t de,int16_t pwm){return fb?FB_FuzzyRule_SetRule(&fb->ruleEngine,e,de,pwm):false;}
